---
name: Checks

on: [ push ]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          ports: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
#          sudo apt install -y postgresql postgresql-contrib
#          sudo systemctl start postgresql.service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate

      - name: Run tests
        run: python manage.py test
